import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Sora } from "next/font/google";
import Navigation from "@/components/layout/client/navigation";
import { ReduxProvider } from "@/components/layout/shared/redux/provider";
import { Toaster } from "@/components/ui/sonner";
const sora = Sora({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} antialiased  bg-[var(--color-cf-background)]`}
      >
        <ReduxProvider>
          <SessionProvider>
            <Toaster position="top-center" richColors />
            {/* <Navigation></Navigation> */}
            {children}
          </SessionProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
